### ISSUE TITLE
Doesn't work with Zepto 1.1.6

### ISSUE THREAD

**Issue by lackneets** [jsor/lity#43]
Try to combine lity with zepto...
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.6/zepto.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lity/1.6.6/lity.min.js"></script>

<a href="http://placehold.it/800x800?.png" class="item" data-lity><img src="http://placehold.it/200x200" alt=""></a>
```

Got
```
lity.min.js:4 Uncaught TypeError: b.Deferred is not a function
```

[jsfiddle] (https://jsfiddle.net/lackneets/p2s3hgv0/)

**Comment by jsor** [comment]
You need to load the [deferred module](https://github.com/madrobby/zepto/blob/master/src/deferred.js) which is not included in the cdnjs build.

**Comment by jsor** [comment]
I've added a note to the README in 58a19a982fab00c3a2cbcaa7cc34b7a860841e79.
